### ISSUE TITLE
Margins

### ISSUE THREAD

**Issue by Fale** [gregturn/asciidoctor-packt#25]
Packt margins are pretty big (4 from each border) while asciidoctor created much smaller margins.

**Comment by gregturn** [comment]
Yeah, I didn't realize the margins they sent me were faulty until the Word docs for the pre-finals arrived. Planning to tune this.

**Comment by gregturn** [comment]
@Fale I opened my e-book copy of Learning Spring Boot and lined it up with my manuscript. I deduced that margins were 1.5in left and right, with 1in top and bottom.

I updated the paper size and the margins, and things look MUCH better. Now it isn't perfect because they naturally apply inline code to their custom font during publication. However, things like code listings will DEFINITELY wrap based on proper margins. So I can make print outs look right.

Cheers.
